baseURL = "/"
languageCode = "zh-cn"
title = "我的创作导航站"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  defaultTheme = "auto"
  description = "AIGC | 指弹吉他 | 法语 | 小说 | 游戏 | 开源工具"
  keywords = ["AIGC", "指弹", "法语", "小说", "开源工具"]
  copyright = "© 2026"

  enableSearch = true
  ShowReadingTime = false
  ShowWordCount = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = false
  disableAnchorCopy = true
  fontSize = "1rem"
  hideFooterWhenScrolling = true

[menu]
  [[menu.main]]
    name = "🏠 首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "🎮 娱乐专栏"
    url = "/entertainment/"
    weight = 2
  [[menu.main]]
    name = "📚 学习空间"
    url = "/study/"
    weight = 3
  [[menu.main]]
    name = "🔧 魔法工具"
    url = "/toolzone/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
